openapi: 3.1.0
info:
  title: app
  version: version
paths:
  /:
    post:
      parameters:
        - in: query
          name: query
          example: string
          description: query
          schema:
            type: string
        - in: header
          name: Content-Type
          example: application/json
          description: Content-Type
          schema:
            type: string
        - in: header
          name: hack
          example: The planet
          description: hack
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
                - body
      responses:
        "200":
          description: Response 200 - PostRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  root:
                    type: boolean
                required:
                  - root
                examples:
                  - root: true
    get:
      parameters:
        - in: query
          name: queryString
          example: string
          description: queryString
          schema:
            type: string
        - in: header
          name: Content-Type
          example: application/json
          description: Content-Type
          schema:
            type: string
        - in: header
          name: hack
          example: The planet
          description: hack
          schema:
            type: string
      responses:
        "400":
          description: Response 400 - GetRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
                examples:
                  - errors:
                      - Required
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags:
  - name: PostRequest
    description: PostRequest
  - name: GetRequest
    description: GetRequest
servers:
  - url: http://0.0.0.0:4000
