openapi: 3.1.0
info:
  title: app
  version: version
paths:
  /:
    post:
      parameters:
        - in: header
          name: Content-Type
          example: application/json
          description: Content-Type
          schema:
            type: string
      tags:
        - PostRequest
      servers:
        - &a1
          url: http://localhost:4000
        - &a2
          url: http://0.0.0.0:1337
      description: PostRequest
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
                - body
            examples:
              value:
                value: '{"body":"string"}'
      responses:
        "200":
          description: Response 200 - PostRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  root:
                    type: boolean
                required:
                  - root
              examples:
                value:
                  value: '{"root":true}'
    get:
      parameters:
        - in: query
          name: QUALQUER_COISA
          example: TYPE_IN_QUERY_STRING_GET
          description: QUALQUER_COISA
          schema:
            type: string
        - in: header
          name: Content-Type
          example: application/json
          description: Content-Type
          schema:
            type: string
      tags:
        - GetRequest
      servers:
        - *a1
        - *a2
      description: GetRequest
      responses:
        "400":
          description: Response 400 - GetRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                  - errors
              examples:
                value:
                  value: '{"errors":["Required"]}'
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags:
  - name: PostRequest
    description: PostRequest
  - name: GetRequest
    description: GetRequest
servers:
  - *a1
  - *a2
  - url: http://0.0.0.0:3000
